In [1]:
import tensorflow as tf

In [2]:
a = tf.add(3,5)
sess = tf.Session()
print(sess.run(a))
sess.close()

8


# Lecture 2

## Visualize it with TensorBoard

In [3]:
# aşağıdaki kodları tensorboard.py dosyasına yazıp komut satırından çalıştırdık.
'''import tensorflow as tf
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a,b)
with tf.Session() as sess:
    # add this line to use TensorBoard
    writer = tf.summary.FileWriter('C:\\Users\\toshiba\\SkyDrive\\veribilimi.co\\codes\\TensorFlowTraining\\Tensorflow_For_Deep_Learning_Research_Videos\\graphs', sess.graph)
    print(sess.run)

writer.close()
'''

"import tensorflow as tf\na = tf.constant(2)\nb = tf.constant(3)\nx = tf.add(a,b)\nwith tf.Session() as sess:\n    # add this line to use TensorBoard\n    writer = tf.summary.FileWriter('C:\\Users\\toshiba\\SkyDrive\\veribilimi.co\\codes\\TensorFlowTraining\\Tensorflow_For_Deep_Learning_Research_Videos\\graphs', sess.graph)\n    print(sess.run)\n\nwriter.close()\n"

TensorBoard'ı iyi öğren çünkü karmaşık modellerde çok işe yarayacak. Yukarıdaki kodu .py uzantılı bir program haline getirip komut satırından çalıştır. Sonra yine komut satırına
python tensor.py
tensorboard --logdir="C:\tensorflow\graphs" --port 6006

## Değişkenlere TensorBoard'da görünecek isimler vermek

In [4]:
# aşağıdaki kodları tensorboard_named.py dosyasına yazıp komut satırından çalıştırdık.
import tensorflow as tf
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a,b, name="add")
with tf.Session() as sess:
    # add this line to use TensorBoard
    writer = tf.summary.FileWriter('C:\\Users\\toshiba\\SkyDrive\\veribilimi.co\\codes\\TensorFlowTraining\\Tensorflow_For_Deep_Learning_Research_Videos\\graphs', sess.graph)
    print(sess.run)

writer.close()

<bound method BaseSession.run of <tensorflow.python.client.session.Session object at 0x00000225CED98F28>>


# Constants (Sabitler)

In [5]:
# tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)
# name: TensorBoard'da grafik arayüzde görünecek isim
# 

In [6]:
a = tf.constant(2, shape=[2,2], verify_shape=True)

TypeError: Expected Tensor's shape: (2, 2), got ().

In [7]:
# Yukarıdaki kod hata verdi çünkü ben hem sabiti 2 olarak verdim 
# hem de boyutunu 2x2 verdim ayrıca boyutu da doğrula dedim.

In [8]:
a = tf.constant(2, shape=[2,2])
a

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [9]:
# verify_shape parametresini kaldırdım. Aslında varsayılan olarak verify_shape=False oldu
# Bu sefer kod hata vermedi

In [10]:
# Sabitlerimizi görmek için interaktif oturumu başlatıyoruz.
tf.InteractiveSession()

In [11]:
a.eval()

array([[2, 2],
       [2, 2]])

In [12]:
# Eğer tanımladığımız sabit ile şekil uyumsuz ise son elemen şeklin tamaında kullanılır.
b = tf.constant([2,1], shape=[3,3])
b.eval()

array([[2, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
a = tf.constant([2,2], name="a")
b = tf.constant([[0,1], [2,3]], name="b")
x = tf.add(a,b, name="add")
x.eval()

array([[2, 3],
       [4, 5]])

In [14]:
y = tf.multiply(a,b, name="mul")
y.eval()

array([[0, 2],
       [4, 6]])

# Tensors filled with specific value
tf.zeros(shape, dtype=tf.float32, name=None)
Tüm elemanları sıfır olan bir tensor oluşturur. numpy.zeros gibi

In [15]:
zeros = tf.zeros([2,3], tf.int32)
zeros.eval()

array([[0, 0, 0],
       [0, 0, 0]])

## Başka bir tensoru kullanarak sıfırlarla doldurma
Aynı şekilde kendi vereceğimiz şekil haricinde başka bir tensoru da şekil olarak verebiliriz.
tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
Farklı bir tip belirtilmedikçe aynı şekildeki tensor içine sıfırları doldurur. numpy.zeros_like ile benzer.

In [16]:
input_tensor = tf.constant([[0,1],[2,3],[4,5]])
mytensor = tf.zeros_like(input_tensor)
mytensor.eval()

array([[0, 0],
       [0, 0],
       [0, 0]])

## Belirli bir değer ile Tensor oluşturma
tf.ones(shape, dtype=tf.float, name=None)

tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)

In [17]:
input_tensor = tf.constant([[0,1],[2,3],[4,5]])
mytensor = tf.ones_like(input_tensor)
mytensor.eval()

array([[1, 1],
       [1, 1],
       [1, 1]])

In [18]:
mytensor = tf.fill([2,3], 8)
mytensor.eval()

array([[8, 8, 8],
       [8, 8, 8]])

## Constants as sequences
tf.linspace(start, stop, num, name=None)
tf.range(start, limit=None, delta=1, dtype=None, name='range')

In [19]:
tf.lin_space(10.0, 13.0, 4).eval()

array([ 10.,  11.,  12.,  13.], dtype=float32)

In [20]:
tf.range(1, 18, 3).eval()

array([ 1,  4,  7, 10, 13, 16])

In [21]:
tf.range(5).eval()

array([0, 1, 2, 3, 4])

## Randomly Generated Constants

In [22]:
'''tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
tf.truncated_normal(shape, mena=0.0, stddev=1.0, dtype=tf.float32, seed=None)
tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None)
tf.random_shuffle(value, seed=None, name=None)
tf.random_crop(value, size, seed=None, name=None)
tf.multinomial(logits=, num_samples=, seed=None, name=None)
tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)
'''

'tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)\ntf.truncated_normal(shape, mena=0.0, stddev=1.0, dtype=tf.float32, seed=None)\ntf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None)\ntf.random_shuffle(value, seed=None, name=None)\ntf.random_crop(value, size, seed=None, name=None)\ntf.multinomial(logits=, num_samples=, seed=None, name=None)\ntf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None)\n'

In [23]:
a = tf.constant([[2,1],[2,2],[3,5]])
tf.random_shuffle(a)

<tf.Tensor 'RandomShuffle:0' shape=(3, 2) dtype=int32>

In [24]:
tf.random_shuffle(a).eval()

array([[3, 5],
       [2, 1],
       [2, 2]])

In [25]:
tf.random_shuffle(a).eval()

array([[3, 5],
       [2, 2],
       [2, 1]])

In [26]:
tf.random_shuffle(a).eval()

array([[3, 5],
       [2, 2],
       [2, 1]])