# Bölüm 1 Hazırlık

# Kütüphaneleri İndirme

In [1]:
# Import libs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Veriyi Yükleme

In [2]:
# Import dataset
dataset = pd.read_csv("C:\\Users\\toshiba\\SkyDrive\\veribilimi.co\\Datasets\\Udemy_A_Z_Deep_Learning\\Churn_Modelling.csv")

In [3]:
# veri setine bakış
dataset.head()

# Exited hedef değişken

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
len(dataset.columns)

14

In [5]:
# Bağımlı ve bağımsız değişkenleri ayırma
# RowNumber, CustomerId, Surname hedef değişkeni tahmin etme bakımından işe yaramaz. Bu yüzden 0,1,2 indeksli nitelikleri
# Nitelikler matrisine dahil etmiyoruz. Yukarıda kaç tane nitelik olduğunu yazdırmıştık. Şimdi 0,1,2 hari ise 3'ten başlayacak. 
# Python'da indeks değeri 0'dan başladığına ve 14 nitalik olduğuna göre son niteliğin indeks değeri 13 olacaktır. iloc ile sütun
#seçerken ilk değer dahil ikinci değer hariçtir. bu sebeple 3'ü dahil 13'ü hariç tutacağız. Çünkü son indeks değeri Exited yani
# hedef değişkene geliyor. İlk : tüm satırlar "," sonrası sütunlardan seçilecek filtre. 3:13 demek 3 dahil 13 hariç indeksli
# sütunları seç demek

X = dataset.iloc[:,3:13].values

# Hedef niteliğimiz 13. indekste idi. O sebeple : ile tüm satırları "," den sonra 13 ile hedef niteliğin indeksini seçiyoruz.
y = dataset.iloc[:,13].values

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ..., 
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [8]:
type(X)

numpy.ndarray

In [9]:
type(y)

numpy.ndarray


# Veri setini eğitim ve test olarak bölmeden önce mutlaka kategorik nitelikleri halletmek gerekir.

In [10]:
# Hedef nitelik 0 ve 1 olmak üzere zaten nümerik değer olduğu için onu LabelEncoder ile kodlamaya gerek yok.
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# X nitelikler matrisini incelediğimizde 1'inci indekste Geography 2'nci indekste Gender'ın kategorik olduğunu görüyoruz.
# Önce Geagraphy için LabelEncoder yaratalım
labelEncoder_Geo = LabelEncoder()
X[:, 1] = labelEncoder_Geo.fit_transform(X[:, 1])

# Şimdi Gender için
labelEncoder_Gender = LabelEncoder()
X[:,2] = labelEncoder_Gender.fit_transform(X[:,2])

# Gender binary olduğu için onu oneHot yapmaya gerek yok. Ancak Geography üç değerli olduğu için onu oneHot (Gölge değişken)
# yapmalıyız. Bunun için OneHotEncoder sınıfını kullanacağız.
# Nesneyi oluşturalım ve dönüştüreceğimiz sütunların indeksinden oluşan listeyi parametre verelim. Burada sadece [1] çünkü
# tek bir tane 
oneHotEncoder = OneHotEncoder(categorical_features=[1])

# nesnemizin fit_transform() metodunu kullanarak Geography niteliğini gölge değişkenlere çeviriyoruz ve X'e ekliyoruz.
X = oneHotEncoder.fit_transform(X).toarray()

In [11]:
X.shape

(10000, 12)

In [12]:
# Gölge Değişken Tuzağından kurtulmak için Yeni oluşturulan gölge değişkenlerden birini çıkaralım
X = X[:,1:]

In [13]:
X.shape

(10000, 11)

# Eğitim ve Test Seti olarak Ayırmak

In [14]:
from sklearn.model_selection import train_test_split

#Sıralamaya dikkat. Aynı sonuçlar için random_state değeri aynı olmalıdır.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

# Feature Scaling

In [15]:
# Nitelikler matrisini (X) StandardScaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
X_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ..., 
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

# Bölüm 2 ANN

In [17]:
# Keras kütüphanelerini indirme
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


YAPAY SİNİR AĞI NESNESİ OLUŞTURMA

In [18]:
# Yapay sinir ağı iki farklı şekilde başlatılabilir: 1. Katmanlar dizilimi (Sequantial layers) olarak. 2. Graph olarak.
# Birinci yolda sadece yukarıda indirilen Sequantial sınıfından nesne yaratılır. Bu da Karar ağacı, SVM gibi bir sınıflandırıcı olacak.
classifier = Sequential()

# Bir Sinir Ağını Stochastic Gradient Descent ile Eğitmenin Aşamaları

1. Sıfıra yakın rastgele değerler ile ağırlık katsayılarını belirle.
2. Input layera ilk gözlemi(bir satır) her bir düğüme bir nitelik (nitelikler matrisi sütün sayısı kadar) düşecek şekilde ver.
3. Ağı çalıştır ve ilk tahmin y değerini üret.
4. Üretilen y ile tahmin edilen y arasındaki hatayı hesapla.
5. Hesaplanan hatayı geri besleme olarak gönder ve her bir ağırlık katsayısını güncelle.
6. 1 ve 5 arasını ya her bir satırdan sonra veya belli bir satır sayısından (grup-batch) sonra tekrarla.
7. Veri setindeki tüm satırların bitmesi bir epoch oluşturur. Bunu defalarca tekrarla.

GİRDİ VE İLK GİZLİ KATMANI EKLEME

In [19]:
# classifier nesnesinin add() metodu içine Dense() Sınıfının nesnesnesini parametre olarak veriyoruz.
# Dense içindeki ilk parametre 
# kernel_initializer (eski init): Başlangıç ağırlıklarını belirler. uniform fonksiyonunu kullanıyoruz.
# input_dim: Yapay sinir ağı nesnesine ilk katman ekleme işlemi yapılırken mutlaka girdi katmanında kaç düğüm olacağı bildirilir.
# aksi halde ilk gizli katman kendisine kaç düğümden bağlantı olacak bilemez. 
# Bu rakam nitelikler matrisindeki sütun sayısıdır yani 11
# units (eski:output_dim): Bu sayının nasıl verileceğine dair sağlam bir kural yok. Biraz sanatkarlık ve tecrübe
# gerektiriyor. Tecrübeye dayalı ipucu: Girdi ve çıktı düğüm sayısının ortalamasını verebilirsin. 
# Bu örnekte (11+1=12/2=6) Ya da parametre tuning tekniklerini kullanabilirsin.
# activation: Gizli düğümler için rectifier çıktı düğüm için sigmoid olsun. Rectifier action parametresinde relu olarak tanımlı


classifier.add(Dense(kernel_initializer = 'uniform', input_dim = 11, units = 6,  activation = 'relu'))


İKİNCİ GİZLİ KATMANI EKLEME

In [20]:
# İkinci Gizli Katmanı Eklemek

# Yukarıda ilk gizli katman ve düğüm sayısı belli olduğu için burada input_dim parametresi kullanmaya gerek yok.
# Gizli katman sayısını (units) aynı tutuyoruz. kaba formül kullandık yine.
classifier.add(Dense(kernel_initializer = 'uniform', units = 4,  activation = 'relu'))


ÇIKTI KATMANI (OUTPUT LAYER) EKLEME

In [21]:
# Bu katmanın bir öncekinden farkı düğüm sayısı ve activasyon fonksiyonu olacak

classifier.add(Dense(kernel_initializer = 'uniform', units = 1,  activation = 'sigmoid'))

YAPAY SINIR AĞINI DERLEME (COMPILE ANN)

In [22]:
# optimizer: Stochastic Gradient Descent'i temsilen adam
# loss: SGD'ni optimizasyonu için kullanılacak loss function. Tahmin y ile gerçek ye değeri arasını hesaplayıp en optimal değeri
# SGD'ye buldurur. Logaritmik loss function. Binary olduğu için binary_crossentropy kullanıyoruz.
# metrics: İlave olarak burada model değerlendirme kriterleri belirlenir. Bir liste halinde verilir. Biz şimdilik sadece accuracy veriyoruz.


classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Yapay Sinir Ağını Eğitim Verisi ile Eğitmek

In [23]:
classifier.fit(X_train, y_train, batch_size=5, epochs=200)

Epoch 1/200
8000/8000 [==============================] - 2s 218us/step - loss: 0.5780 - acc: 0.7961
Epoch 2/200
8000/8000 [==============================] - 1s 169us/step - loss: 0.4699 - acc: 0.8145
Epoch 3/200
8000/8000 [==============================] - 1s 162us/step - loss: 0.4380 - acc: 0.8235
Epoch 4/200
8000/8000 [==============================] - 1s 164us/step - loss: 0.4282 - acc: 0.8295
Epoch 5/200
8000/8000 [==============================] - 1s 165us/step - loss: 0.4218 - acc: 0.8313
Epoch 6/200
8000/8000 [==============================] - 1s 167us/step - loss: 0.4163 - acc: 0.8314
Epoch 7/200
8000/8000 [==============================] - 1s 171us/step - loss: 0.4080 - acc: 0.8365
Epoch 8/200
8000/8000 [==============================] - 1s 169us/step - loss: 0.3960 - acc: 0.8399
Epoch 9/200
8000/8000 [==============================] - 1s 172us/step - loss: 0.3804 - acc: 0.8465
Epoch 10/200
8000/8000 [==============================] - 1s 168us/step - loss: 0.3677 - acc: 0.8519

8000/8000 [==============================] - 1s 165us/step - loss: 0.3331 - acc: 0.8643
Epoch 82/200
8000/8000 [==============================] - 1s 167us/step - loss: 0.3330 - acc: 0.8634
Epoch 83/200
8000/8000 [==============================] - 1s 169us/step - loss: 0.3328 - acc: 0.8636
Epoch 84/200
8000/8000 [==============================] - 1s 170us/step - loss: 0.3334 - acc: 0.8645
Epoch 85/200
8000/8000 [==============================] - 1s 170us/step - loss: 0.3326 - acc: 0.8644
Epoch 86/200
8000/8000 [==============================] - 1s 172us/step - loss: 0.3334 - acc: 0.8645
Epoch 87/200
8000/8000 [==============================] - 1s 172us/step - loss: 0.3330 - acc: 0.8654
Epoch 88/200
8000/8000 [==============================] - 1s 171us/step - loss: 0.3335 - acc: 0.8638
Epoch 89/200
8000/8000 [==============================] - 1s 173us/step - loss: 0.3325 - acc: 0.8660
Epoch 90/200
8000/8000 [==============================] - 1s 173us/step - loss: 0.3320 - acc: 0.8650
Epo

8000/8000 [==============================] - 1s 169us/step - loss: 0.3321 - acc: 0.8635
Epoch 162/200
8000/8000 [==============================] - 1s 171us/step - loss: 0.3317 - acc: 0.8635
Epoch 163/200
8000/8000 [==============================] - 1s 167us/step - loss: 0.3320 - acc: 0.8638
Epoch 164/200
8000/8000 [==============================] - 1s 170us/step - loss: 0.3324 - acc: 0.8631
Epoch 165/200
8000/8000 [==============================] - 1s 171us/step - loss: 0.3324 - acc: 0.8640
Epoch 166/200
8000/8000 [==============================] - 1s 170us/step - loss: 0.3320 - acc: 0.8643
Epoch 167/200
8000/8000 [==============================] - 1s 169us/step - loss: 0.3322 - acc: 0.8624
Epoch 168/200
8000/8000 [==============================] - 1s 168us/step - loss: 0.3317 - acc: 0.8638
Epoch 169/200
8000/8000 [==============================] - 1s 169us/step - loss: 0.3320 - acc: 0.8636
Epoch 170/200
8000/8000 [==============================] - 1s 170us/step - loss: 0.3320 - acc: 0

# Yapay Sinir Ağını Test verisi ile Test Etmek

In [24]:
y_pred = classifier.predict(X_test)

In [25]:
y_pred

array([[ 0.28097957],
       [ 0.32140738],
       [ 0.23984791],
       ..., 
       [ 0.16705167],
       [ 0.15123393],
       [ 0.20101278]], dtype=float32)

In [26]:
y_pred = (y_pred>0.5)

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1495,  100],
       [ 181,  224]])

In [31]:
cm[1][0]

181

In [28]:
# Elle accuracy tekrar hesaplayalım (Doğru tahmin edilenlerin tüm test setine oranı)
acc = (cm[0][1]+cm[1][1])/(cm[0][0]+cm[0][39+286+116)
acc

0.8387581372058087